"""
Preview helper functions
"""

import os
import pathlib
import tempfile
from unittest import TestCase
from unittest.mock import patch

import pandas
import pyarrow.parquet as pq
from py_w3c.validators.html.validator import HTMLValidator

from t4_lambda_shared.preview import (
    FCS_SCATTER_LIMIT,
    FCS_SCATTER_RANDOM_SEED,
    _build_fcs_scatter_spec,
    _extract_fcs_channel_names,
    _parse_fcs_text_segment,
    extract_excel,
    extract_fcs,
    extract_parquet,
    get_bytes,
    get_preview_lines,
)

TEST_EXTRACT_PARQUET_MAX_BYTES = 10_000
BASE_DIR = pathlib.Path(__file__).parent / 'data'
PREVIEW_FCS_DIR = BASE_DIR.parents[2] / 'preview' / 'test' / 'data' / 'fcs'
FCS_COLUMNS_STRING = 'FSC-A,SSC-A,FL1-A,FL2-A,FL3-A,FL4-A,FSC-H,SSC-H,FL1-H,FL2-H,FL3-H,FL4-H,Width,Time'
ACCEPTABLE_ERROR_MESSAGES = [
    'Start tag seen without seeing a doctype first. Expected "<!DOCTYPE html>".',
    'Element "head" is missing a required instance of child element "title".',
    'Element "style" not allowed as child of element "div" in this context. '
    '(Suppressing further errors from this subtree.)',
    'The "border" attribute on the "table" element is obsolete. Consider specifying "img { border: 0; }" in CSS instead.',
]


def normalize_quotes(text):
    """Normalize Unicode curly quotes to ASCII straight quotes for comparison.

    The W3C HTML validator service now returns error messages with Unicode
    curly quotes (" " ' ') instead of ASCII straight quotes (" ').
    This function normalizes both quote styles to enable consistent comparison.
    """
    return text.replace('\u201c', '"').replace('\u201d', '"').replace('\u2018', "'").replace('\u2019', "'")


def iterate_chunks(file_obj, chunk_size=4096):
    return iter(lambda: file_obj.read(chunk_size), b'')


class TestPreview(TestCase):
    """Tests the preview functions"""

    def test_extract_parquet(self):
        file = BASE_DIR / 'amazon-reviews-1000.snappy.parquet'
        cell_value = '<td>TSD Airsoft/Paintball Full-Face Mask, Goggle Lens</td>'

        with patch('t4_lambda_shared.preview.get_available_memory') as mem_mock:
            mem_mock.return_value = 1
            with open(file, mode='rb') as parquet:
                body, info = extract_parquet(parquet, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
                assert all(bracket in body for bracket in ('<', '>'))
                assert body.count('<') == body.count('>'), 'expected matching HTML tags'
                assert cell_value not in body, 'only expected columns'
                assert 'Skipped rows' in info['warnings']

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, as_html=True, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert cell_value in body, 'missing expected HTML cell'

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, skip_rows=True, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert 'Skipped rows' in info['warnings']
            assert cell_value not in body, 'only expected columns'

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, as_html=False, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert all(bracket not in body for bracket in ('<', '>')), 'did not expect HTML'
            parquet_file = pq.ParquetFile(file)
            assert all(column in info['schema']['names'] for column in parquet_file.schema.names)
            assert [parquet_file.metadata.num_rows, parquet_file.metadata.num_columns] == info['shape'], (
                'Unexpected number of rows or columns'
            )

    def test_excel(self):
        """test XLS, XLSX parsing"""
        test_files = {
            "Revised.Haplogroups.1000G.20140205.xlsx": {
                "contents": [
                    "Continent",
                    "Population",
                    "ID",
                    "Macrohaplogroup",
                    "Haplogroup",
                    "Informative SNPs",
                    "NA19239",
                    "NA19256",
                    "E1b1a1a1g1a2",
                ]
            },
            "lclarke_phase1_sequence_stats_20120330.xls": {
                "contents": [
                    "Breakdown of data generated by project, technology, submitting centre",
                    "92219554043",
                    "90363687334",
                ]
            },
        }
        vld = HTMLValidator()
        for file, expected_data in test_files.items():
            in_file = os.path.join(BASE_DIR, "excel", file)
            with open(in_file, mode="rb") as excel:
                for html in [False, True]:
                    body, _ = extract_excel(excel, as_html=html)
                    # print(body)
                    tags = ['<div>', '<tbody>', '<th>', '<td>', '<tr>']
                    if html:
                        vld.validate_fragment(body)
                        assert all(t in body for t in tags)
                        normalized_acceptable = [normalize_quotes(msg) for msg in ACCEPTABLE_ERROR_MESSAGES]
                        serious_errors = [
                            e for e in vld.errors if normalize_quotes(e["message"]) not in normalized_acceptable
                        ]
                        assert not serious_errors
                        print(vld.warnings)
                    else:
                        assert not any(t in body for t in tags)
                    assert all(c in body for c in expected_data["contents"])

    def test_fcs(self):
        """test FCS parsing"""
        plotted_files = [
            {
                'path': BASE_DIR / 'fcs' / 'normal.fcs',
                'metadata_key': '#P1MaxUsefulDataChannel',
                'metadata_value': '491519',
            },
            {
                'path': PREVIEW_FCS_DIR / 'accuri-ao1.fcs',
                'metadata_key': '#P1MaxUsefulDataChannel',
                'metadata_value': '491519',
            },
        ]
        for expected_data in plotted_files:
            with open(expected_data['path'], mode='rb') as fcs:
                body, info = extract_fcs(fcs)

                assert '<th>FL3-H</th>' in body
                assert 'warnings' not in info
                assert info['vegaLite']['title']['text'] == 'FSC-A vs SSC-A'
                assert info['vegaLite']['title']['subtitle'] == 'Showing 191 events'
                assert info['vegaLite']['encoding']['x']['title'] == 'FSC-A'
                assert info['vegaLite']['encoding']['y']['title'] == 'SSC-A'
                assert len(info['vegaLite']['data']['values']) == 191
                assert expected_data['metadata_key'].lower() in {key.lower() for key in info['metadata'].keys()}
                assert expected_data['metadata_value'] in info['metadata'].values()

                fcs.seek(0)
                body, _ = extract_fcs(fcs, as_html=False)
                assert body == FCS_COLUMNS_STRING

        metadata_only_files = [
            {
                'path': BASE_DIR / 'fcs' / 'meta_only.fcs',
                'metadata_key': '$FIL',
                'metadata_value': 'Compensation Controls_G710 Stained Control.fcs',
                'channel_names': 'FSC-A,FSC-H,SSC-A,R780-A,B515-A,V450-A,V545-A,G560-A,G610-A,G660-A,G710-A,Time',
            },
            {
                'path': PREVIEW_FCS_DIR / '3215apc 100004.fcs',
                'metadata_key': 'creator',
                'metadata_value': 'FlowJoCollectorsEdition 7.5.109.8',
            },
        ]
        for expected_data in metadata_only_files:
            with open(expected_data['path'], mode='rb') as fcs:
                body, info = extract_fcs(fcs)

                assert body == ""
                assert info['warnings'].startswith('Metadata only. Parse exception:')
                assert 'vegaLite' not in info
                assert expected_data['metadata_key'].lower() in {key.lower() for key in info['metadata'].keys()}
                assert expected_data['metadata_value'] in info['metadata'].values()
                if expected_data.get('channel_names'):
                    assert info['metadata']['_channel_names_'] == expected_data['channel_names']

        with open(PREVIEW_FCS_DIR / 'bad.fcs', mode='rb') as fcs:
            body, info = extract_fcs(fcs)

        assert body == ""
        assert info['warnings'].startswith('Unable to parse data or metadata:')
        assert 'metadata' not in info
        assert 'vegaLite' not in info

    def test_fcs_scatter_spec_downsamples(self):
        data = pandas.DataFrame(
            {
                'alpha': range(FCS_SCATTER_LIMIT * 2),
                'beta': range(FCS_SCATTER_LIMIT * 2, FCS_SCATTER_LIMIT * 4),
            }
        )

        spec = _build_fcs_scatter_spec(data)

        assert spec['title']['text'] == 'alpha vs beta'
        assert spec['title']['subtitle'] == f'Downsampled to {FCS_SCATTER_LIMIT} events'
        assert spec['encoding']['x']['title'] == 'alpha'
        assert spec['encoding']['y']['title'] == 'beta'
        assert len(spec['data']['values']) == FCS_SCATTER_LIMIT
        expected = data[['alpha', 'beta']].sample(
            n=FCS_SCATTER_LIMIT,
            random_state=FCS_SCATTER_RANDOM_SEED,
        )
        assert spec['data']['values'][:5] == [
            {'x': alpha, 'y': beta} for alpha, beta in expected.head(5).itertuples(index=False, name=None)
        ]

    def test_fcs_scatter_spec_downsampling_is_seeded(self):
        data = pandas.DataFrame(
            {
                'alpha': range(FCS_SCATTER_LIMIT + 37),
                'beta': range(FCS_SCATTER_LIMIT + 37, (FCS_SCATTER_LIMIT * 2) + 74),
            }
        )

        first = _build_fcs_scatter_spec(data)
        second = _build_fcs_scatter_spec(data)

        assert first['data']['values'] == second['data']['values']

    def test_fcs_scatter_spec_filters_invalid_values(self):
        data = pandas.DataFrame(
            {
                'alpha': [1, float('nan'), float('inf'), float('-inf')],
                'beta': [10, 20, 30, float('nan')],
            }
        )

        spec = _build_fcs_scatter_spec(data, limit=10)

        assert spec['title']['subtitle'] == 'Showing 1 events'
        assert spec['data']['values'] == [{'x': 1.0, 'y': 10.0}]
        assert (
            _build_fcs_scatter_spec(
                pandas.DataFrame(
                    {
                        'alpha': [float('nan'), float('inf')],
                        'beta': [float('nan'), float('-inf')],
                    }
                )
            )
            is None
        )

    def test_parse_fcs_text_segment(self):
        text_segment = b'|$PAR|2|$P1N|FSC-A|$P2S|SSC||A|'
        text_start = 58
        text_end = text_start + len(text_segment) - 1
        header = bytearray(b' ' * 58)
        header[:6] = b'FCS3.0'
        header[10:18] = f'{text_start:>8}'.encode('ascii')
        header[18:26] = f'{text_end:>8}'.encode('ascii')

        with tempfile.NamedTemporaryFile() as fcs:
            fcs.write(header)
            fcs.write(text_segment)
            fcs.flush()

            metadata = _parse_fcs_text_segment(fcs.name)

        assert metadata['$P1N'] == 'FSC-A'
        assert metadata['$P2S'] == 'SSC|A'
        assert _extract_fcs_channel_names(metadata) == 'FSC-A,SSC|A'

    def test_long(self):
        """test a text file with lots of lines"""
        txt = BASE_DIR / 'long.txt'
        max_lines = 500
        max_bytes = 10000
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), None, max_lines, max_bytes)

        assert len(lines) == max_lines, 'unexpected number of lines'
        assert lines[0] == 'Line 1', 'unexpected first line'
        assert lines[-1] == f'Line {max_lines}', 'unexpected last line'

    def test_long_gz(self):
        """test a gzipped text file with lots of lines"""
        txt = BASE_DIR / 'long.txt.gz'
        max_lines = 500
        max_bytes = 10000
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), 'gz', max_lines, max_bytes)

        assert len(lines) == max_lines, 'unexpected number of lines'
        assert lines[0] == 'Line 1', 'unexpected first line'
        assert lines[-1] == f'Line {max_lines}', 'unexpected last line'

    def test_txt_max_bytes(self):
        """test truncation to CATALOG_LIMIT_BYTES"""
        txt = BASE_DIR / 'two-line.txt'
        max_lines = 500
        max_bytes = 5
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), None, max_lines, max_bytes)
        assert len(lines) == 1, 'failed to truncate bytes'
        assert lines[0] == '1234😊', 'failed to truncate bytes'

    def test_txt_max_bytes_one_line(self):
        """test truncation to CATALOG_LIMIT_BYTES"""
        txt = BASE_DIR / 'one-line.txt'
        max_lines = 500
        max_bytes = 8
        chunk_size = 10
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj, chunk_size), None, max_lines, max_bytes)
        assert len(lines) == 1, 'failed to truncate bytes'
        assert lines[0] == '🚷🚯', 'failed to truncate bytes'

    def test_bytes(self):
        txt = BASE_DIR / 'long.txt.gz'
        with open(txt, 'rb') as file_obj:
            buffer = get_bytes(file_obj, 'gz')
        lines = buffer.getvalue().splitlines()
        assert lines[0] == b'Line 1'
        assert lines[-1] == b'Line 999'
