"""
Preview helper functions
"""

import json
import os
import pathlib
from unittest import TestCase
from unittest.mock import patch

import pandas
import pyarrow.parquet as pq
from py_w3c.validators.html.validator import HTMLValidator

from t4_lambda_shared.preview import (
    FCS_GRID_PANEL_SIZE,
    FCS_GRID_SPACING,
    FCS_MAX_PANELS,
    FCS_PANEL_COLUMNS,
    FCS_SCATTER_RANDOM_SEED,
    FCS_SCATTER_TOTAL_LIMIT,
    FCS_SINGLE_PANEL_HEIGHT,
    _axis_label,
    _build_fcs_scatter_spec,
    _fcs_channel_markers,
    _select_fcs_panels,
    extract_excel,
    extract_fcs,
    extract_parquet,
    get_bytes,
    get_preview_lines,
)

TEST_EXTRACT_PARQUET_MAX_BYTES = 10_000
BASE_DIR = pathlib.Path(__file__).parent / 'data'
ACCEPTABLE_ERROR_MESSAGES = [
    'Start tag seen without seeing a doctype first. Expected "<!DOCTYPE html>".',
    'Element "head" is missing a required instance of child element "title".',
    'Element "style" not allowed as child of element "div" in this context. '
    '(Suppressing further errors from this subtree.)',
    'The "border" attribute on the "table" element is obsolete. Consider specifying "img { border: 0; }" in CSS instead.',
]


def normalize_quotes(text):
    """Normalize Unicode curly quotes to ASCII straight quotes for comparison.

    The W3C HTML validator service now returns error messages with Unicode
    curly quotes (" " ' ') instead of ASCII straight quotes (" ').
    This function normalizes both quote styles to enable consistent comparison.
    """
    return text.replace('\u201c', '"').replace('\u201d', '"').replace('\u2018', "'").replace('\u2019', "'")


def iterate_chunks(file_obj, chunk_size=4096):
    return iter(lambda: file_obj.read(chunk_size), b'')


class TestPreview(TestCase):
    """Tests the preview functions"""

    def test_extract_parquet(self):
        file = BASE_DIR / 'amazon-reviews-1000.snappy.parquet'
        cell_value = '<td>TSD Airsoft/Paintball Full-Face Mask, Goggle Lens</td>'

        with patch('t4_lambda_shared.preview.get_available_memory') as mem_mock:
            mem_mock.return_value = 1
            with open(file, mode='rb') as parquet:
                body, info = extract_parquet(parquet, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
                assert all(bracket in body for bracket in ('<', '>'))
                assert body.count('<') == body.count('>'), 'expected matching HTML tags'
                assert cell_value not in body, 'only expected columns'
                assert 'Skipped rows' in info['warnings']

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, as_html=True, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert cell_value in body, 'missing expected HTML cell'

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, skip_rows=True, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert 'Skipped rows' in info['warnings']
            assert cell_value not in body, 'only expected columns'

        with open(file, mode='rb') as parquet:
            body, info = extract_parquet(parquet, as_html=False, max_bytes=TEST_EXTRACT_PARQUET_MAX_BYTES)
            assert all(bracket not in body for bracket in ('<', '>')), 'did not expect HTML'
            parquet_file = pq.ParquetFile(file)
            assert all(column in info['schema']['names'] for column in parquet_file.schema.names)
            assert [parquet_file.metadata.num_rows, parquet_file.metadata.num_columns] == info['shape'], (
                'Unexpected number of rows or columns'
            )

    def test_excel(self):
        """test XLS, XLSX parsing"""
        test_files = {
            "Revised.Haplogroups.1000G.20140205.xlsx": {
                "contents": [
                    "Continent",
                    "Population",
                    "ID",
                    "Macrohaplogroup",
                    "Haplogroup",
                    "Informative SNPs",
                    "NA19239",
                    "NA19256",
                    "E1b1a1a1g1a2",
                ]
            },
            "lclarke_phase1_sequence_stats_20120330.xls": {
                "contents": [
                    "Breakdown of data generated by project, technology, submitting centre",
                    "92219554043",
                    "90363687334",
                ]
            },
        }
        vld = HTMLValidator()
        for file, expected_data in test_files.items():
            in_file = os.path.join(BASE_DIR, "excel", file)
            with open(in_file, mode="rb") as excel:
                for html in [False, True]:
                    body, _ = extract_excel(excel, as_html=html)
                    # print(body)
                    tags = ['<div>', '<tbody>', '<th>', '<td>', '<tr>']
                    if html:
                        vld.validate_fragment(body)
                        assert all(t in body for t in tags)
                        normalized_acceptable = [normalize_quotes(msg) for msg in ACCEPTABLE_ERROR_MESSAGES]
                        serious_errors = [
                            e for e in vld.errors if normalize_quotes(e["message"]) not in normalized_acceptable
                        ]
                        assert not serious_errors
                        print(vld.warnings)
                    else:
                        assert not any(t in body for t in tags)
                    assert all(c in body for c in expected_data["contents"])

    def test_fcs(self):
        """test FCS parsing"""
        # store test files and expectations
        test_files = {
            'normal.fcs': {
                'columns_string': 'FSC-A,SSC-A,FL1-A,FL2-A,FL3-A,FL4-A,FSC-H,SSC-H,FL1-H,FL2-H,FL3-H,FL4-H,Width,Time',
                'in_body': '<th>FL3-H</th>',
                'in_meta_keys': '#P1MaxUsefulDataChannel',
                'in_meta_values': '491519',
                'has_warnings': False,
                # FSC/SSC + fluorescence channels -> canonical multi-panel gating grid.
                'gating_grid': True,
                'events': 191,
            },
            'meta_only.fcs': {
                'in_meta_keys': '_channel_names_',
                'in_meta_values': 'Compensation Controls_G710 Stained Control.fcs',
                'has_warnings': True,
            },
        }
        for file, expected_data in test_files.items():
            in_file = os.path.join(BASE_DIR, 'fcs', file)

            with open(in_file, mode='rb') as fcs:
                body, info = extract_fcs(fcs)
                if body != "":
                    assert expected_data['in_body'] in body
                    assert not expected_data.get('has_warnings')
                else:
                    assert expected_data['has_warnings']
                    assert info['warnings']
                assert expected_data['in_meta_keys'] in info['metadata'].keys()
                assert expected_data['in_meta_values'] in info['metadata'].values()
                # metadata-only parses can't build a plot
                if expected_data.get('has_warnings'):
                    assert 'vegaLite' not in info
                # the plotted file yields the canonical gating grid, whose first
                # panel is the FSC-A vs SSC-A "Cells" gate
                if expected_data.get('gating_grid'):
                    panels = info['vegaLite']['concat']
                    assert len(panels) > 1
                    first = panels[0]
                    assert first['title']['text'] == 'Cells — FSC-A vs SSC-A'
                    assert first['encoding']['x']['title'] == 'FSC-A'
                    assert first['encoding']['y']['title'] == 'SSC-A'
                    assert len(first['data']['values']) == expected_data['events']
                # when there's a body, check if columns only works
                if expected_data.get('in_body'):
                    # move to start so we can use the file-like a second time
                    fcs.seek(0)
                    body, info = extract_fcs(fcs, as_html=False)
                    assert body == expected_data['columns_string']

    def test_fcs_scatter_spec_downsamples(self):
        # A single (non-canonical) panel gets the whole event budget.
        data = pandas.DataFrame(
            {
                'alpha': range(FCS_SCATTER_TOTAL_LIMIT * 2),
                'beta': range(FCS_SCATTER_TOTAL_LIMIT * 2, FCS_SCATTER_TOTAL_LIMIT * 4),
            }
        )

        spec = _build_fcs_scatter_spec(data)

        # non-canonical channels -> single panel over the first two columns
        assert spec['title']['text'] == 'alpha vs beta'
        assert spec['title']['subtitle'] == f'{FCS_SCATTER_TOTAL_LIMIT} events (downsampled)'
        assert spec['encoding']['x']['title'] == 'alpha'
        assert spec['encoding']['y']['title'] == 'beta'
        assert len(spec['data']['values']) == FCS_SCATTER_TOTAL_LIMIT

    def test_fcs_scatter_spec_downsampling_is_seeded(self):
        data = pandas.DataFrame(
            {
                'alpha': range(FCS_SCATTER_TOTAL_LIMIT + 37),
                'beta': range(FCS_SCATTER_TOTAL_LIMIT + 37, (FCS_SCATTER_TOTAL_LIMIT * 2) + 74),
            }
        )

        first = _build_fcs_scatter_spec(data)
        second = _build_fcs_scatter_spec(data)

        assert first['data']['values'] == second['data']['values']

    def test_fcs_scatter_spec_filters_invalid_values(self):
        data = pandas.DataFrame(
            {
                'alpha': [1, float('nan'), float('inf'), float('-inf')],
                'beta': [10, 20, 30, float('nan')],
            }
        )

        spec = _build_fcs_scatter_spec(data, total_limit=10)

        assert spec['title']['subtitle'] == '1 events'
        assert spec['data']['values'] == [{'x': 1.0, 'y': 10.0}]
        # all-invalid data yields no plot
        assert (
            _build_fcs_scatter_spec(
                pandas.DataFrame(
                    {
                        'alpha': [float('nan'), float('inf')],
                        'beta': [float('nan'), float('-inf')],
                    }
                )
            )
            is None
        )

    def test_fcs_scatter_spec_multi_panel_gating(self):
        # FSC/SSC + fluorescence channels -> canonical gating grid (concat).
        data = pandas.DataFrame(
            {ch: range(10) for ch in ('FSC-A', 'SSC-A', 'FSC-H', 'FL1-A', 'FL2-A', 'FL3-A', 'FL4-A')}
        )

        spec = _build_fcs_scatter_spec(data)

        assert 'concat' in spec and 'encoding' not in spec
        titles = [panel['title']['text'] for panel in spec['concat']]
        assert titles[0] == 'Cells — FSC-A vs SSC-A'
        assert titles[1] == 'Singlets — FSC-H vs FSC-A'
        assert len(spec['concat']) <= FCS_MAX_PANELS
        # explicit square cells (container width is ignored inside a concat)
        assert spec['columns'] == FCS_PANEL_COLUMNS
        assert spec['spacing'] == FCS_GRID_SPACING
        assert spec['resolve'] == {'scale': {'x': 'independent', 'y': 'independent'}}
        assert 'params' not in spec
        for panel in spec['concat']:
            assert panel['width'] == FCS_GRID_PANEL_SIZE
            assert panel['height'] == FCS_GRID_PANEL_SIZE

    def test_fcs_scatter_spec_single_panel_is_responsive(self):
        # A lone panel stays responsive (container width) and keeps the brush.
        data = pandas.DataFrame({'FSC-A': range(10), 'SSC-A': range(10)})

        spec = _build_fcs_scatter_spec(data)

        assert 'concat' not in spec
        assert spec['width'] == 'container'
        assert spec['height'] == FCS_SINGLE_PANEL_HEIGHT
        assert spec['params'] == [{'name': 'brush', 'select': 'interval'}]
        assert spec['encoding']['color']['condition']['param'] == 'brush'

    def test_fcs_scatter_spec_uses_marker_labels(self):
        # $PnS markers should label axes as "<marker> (<channel>)".
        data = pandas.DataFrame({'FSC-A': range(5), 'SSC-A': range(5)})

        spec = _build_fcs_scatter_spec(data, channel_markers={'FSC-A': 'CD3', 'SSC-A': 'CD4'})

        assert spec['encoding']['x']['title'] == 'CD3 (FSC-A)'
        assert spec['encoding']['y']['title'] == 'CD4 (SSC-A)'

    def test_fcs_scatter_spec_multi_panel_marker_labels(self):
        data = pandas.DataFrame({ch: range(10) for ch in ('FSC-A', 'SSC-A', 'FSC-H', 'FL1-A', 'FL2-A')})
        spec = _build_fcs_scatter_spec(data, channel_markers={'FL1-A': 'CD3', 'FL2-A': 'CD4'})
        # Marker labels propagate into the fluorescence panel.
        fl_panel = next(p for p in spec['concat'] if p['title']['text'].startswith('FL1-A'))
        assert fl_panel['encoding']['x']['title'] == 'CD3 (FL1-A)'
        assert fl_panel['encoding']['y']['title'] == 'CD4 (FL2-A)'

    def test_select_fcs_panels_canonical_order(self):
        # Only canonical pairs whose BOTH channels exist, in workflow order.
        cols = ['FSC-A', 'SSC-A', 'FSC-H', 'FL1-A', 'FL2-A']
        panels = _select_fcs_panels(cols)
        assert panels[0] == ('FSC-A', 'SSC-A', 'Cells')
        assert panels[1] == ('FSC-H', 'FSC-A', 'Singlets')
        assert ('FL1-A', 'FL2-A', None) in panels
        # SSC-H is absent, so the "Singlets (SSC)" panel must not appear.
        assert all(p[:2] != ('SSC-H', 'SSC-A') for p in panels)

    def test_select_fcs_panels_caps_at_max(self):
        # All canonical channels present -> capped at FCS_MAX_PANELS.
        cols = ['FSC-A', 'SSC-A', 'FSC-H', 'SSC-H', 'FL1-A', 'FL2-A', 'FL3-A', 'FL4-A']
        panels = _select_fcs_panels(cols)
        assert len(panels) == FCS_MAX_PANELS

    def test_select_fcs_panels_fallback_to_first_two(self):
        # Non-standard channel names -> fall back to the first two columns.
        assert _select_fcs_panels(['alpha', 'beta', 'gamma']) == [('alpha', 'beta', None)]
        # Fewer than two columns -> no panels.
        assert _select_fcs_panels(['solo']) == []

    def test_fcs_channel_markers_parsing(self):
        # Parsers may lower-case keywords to p<idx>n / p<idx>s; blanks are dropped.
        meta = {
            'p1n': 'FSC-A',
            'p1s': '',  # blank marker -> omitted
            'p2n': 'FL1-A',
            'p2s': 'CD3',
            'p3n': 'FL2-A',
            'p3s': 'nan',  # sentinel -> omitted
        }
        assert _fcs_channel_markers(meta) == {'FL1-A': 'CD3'}
        assert _fcs_channel_markers({}) == {}
        # Upper-case $PnN/$PnS variant is also recognized.
        assert _fcs_channel_markers({'$P1N': 'FL1-A', '$P1S': 'CD4'}) == {'FL1-A': 'CD4'}

    def test_fcs_channel_markers_from_reformatted_channels(self):
        # fcsparser reformat_meta=True stores markers in a `_channels_` DataFrame
        # (with `$PnN`/`$PnS` columns) and drops the flat `$P<idx>N` keys.
        channels = pandas.DataFrame(
            {'$PnN': ['FSC-A', 'FL1-A', 'FL2-A'], '$PnS': ['', 'CD3', 'nan']},
            index=[1, 2, 3],
        )
        assert _fcs_channel_markers({'_channels_': channels}) == {'FL1-A': 'CD3'}

    def test_fcs_channel_markers_flat_keys_tolerate_gaps(self):
        # A gap in the flat keys ($P3N missing) must not drop later markers; the
        # loop should skip the gap and still pick up $P4S.
        meta = {
            '$PAR': '4',
            '$P1N': 'FSC-A',
            '$P1S': '',  # blank -> omitted
            '$P2N': 'FL1-A',
            '$P2S': 'CD3',
            # $P3N / $P3S intentionally absent
            '$P4N': 'FL2-A',
            '$P4S': 'CD4',
        }
        assert _fcs_channel_markers(meta) == {'FL1-A': 'CD3', 'FL2-A': 'CD4'}

    def test_fcs_scatter_spec_payload_stays_under_lambda_cap(self):
        # A large multi-panel FCS file must not blow past the preview lambda's
        # 6 MB response cap: the total event budget is shared across all panels.
        lambda_max_out = 6_000_000
        n = FCS_SCATTER_TOTAL_LIMIT * 5  # far more events than the budget
        data = pandas.DataFrame(
            {ch: range(n) for ch in ('FSC-A', 'SSC-A', 'FSC-H', 'SSC-H', 'FL1-A', 'FL2-A', 'FL3-A', 'FL4-A')}
        )

        spec = _build_fcs_scatter_spec(data)

        total_events = sum(len(panel['data']['values']) for panel in spec['concat'])
        assert total_events <= FCS_SCATTER_TOTAL_LIMIT
        # Serialized payload must have real headroom under the cap.
        assert len(json.dumps(spec).encode('utf-8')) < lambda_max_out

    def test_axis_label_dedup_and_fallback(self):
        markers = {'FL1-A': 'CD3', 'FSC-A': 'FSC-A'}
        assert _axis_label('FL1-A', markers) == 'CD3 (FL1-A)'  # marker shown
        assert _axis_label('FSC-A', markers) == 'FSC-A'  # redundant marker skipped
        assert _axis_label('SSC-A', markers) == 'SSC-A'  # no marker -> channel
        assert _axis_label('SSC-A', None) == 'SSC-A'  # None markers tolerated

    def test_long(self):
        """test a text file with lots of lines"""
        txt = BASE_DIR / 'long.txt'
        max_lines = 500
        max_bytes = 10000
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), None, max_lines, max_bytes)

        assert len(lines) == max_lines, 'unexpected number of lines'
        assert lines[0] == 'Line 1', 'unexpected first line'
        assert lines[-1] == f'Line {max_lines}', 'unexpected last line'

    def test_long_gz(self):
        """test a gzipped text file with lots of lines"""
        txt = BASE_DIR / 'long.txt.gz'
        max_lines = 500
        max_bytes = 10000
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), 'gz', max_lines, max_bytes)

        assert len(lines) == max_lines, 'unexpected number of lines'
        assert lines[0] == 'Line 1', 'unexpected first line'
        assert lines[-1] == f'Line {max_lines}', 'unexpected last line'

    def test_txt_max_bytes(self):
        """test truncation to CATALOG_LIMIT_BYTES"""
        txt = BASE_DIR / 'two-line.txt'
        max_lines = 500
        max_bytes = 5
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj), None, max_lines, max_bytes)
        assert len(lines) == 1, 'failed to truncate bytes'
        assert lines[0] == '1234😊', 'failed to truncate bytes'

    def test_txt_max_bytes_one_line(self):
        """test truncation to CATALOG_LIMIT_BYTES"""
        txt = BASE_DIR / 'one-line.txt'
        max_lines = 500
        max_bytes = 8
        chunk_size = 10
        with open(txt, 'rb') as file_obj:
            lines = get_preview_lines(iterate_chunks(file_obj, chunk_size), None, max_lines, max_bytes)
        assert len(lines) == 1, 'failed to truncate bytes'
        assert lines[0] == '🚷🚯', 'failed to truncate bytes'

    def test_bytes(self):
        txt = BASE_DIR / 'long.txt.gz'
        with open(txt, 'rb') as file_obj:
            buffer = get_bytes(file_obj, 'gz')
        lines = buffer.getvalue().splitlines()
        assert lines[0] == b'Line 1'
        assert lines[-1] == b'Line 999'
