"""
APIs for Quilt administrators. 'Registry' refers to Quilt stack backend services, including identity management.
"""

# This wraps code generated by ariadne-codegen to provide a more user-friendly API.

from ..api_keys import APIKey
from . import api_keys, buckets, policies, roles, sso_config, tabulator, users
from .exceptions import (
    BucketNotFoundError,
    InvalidInputError,
    OperationError,
    PolicyArnExistsError,
    PolicyNotFoundError,
    PolicyTitleExistsError,
    Quilt3AdminError,
    RoleAssignedError,
    RoleNameExistsError,
    RoleNameInvalidError,
    RoleNameReservedError,
    RoleNotFoundError,
    RoleSsoConfigConflictError,
    RoleTooManyPoliciesError,
    RoleTypeMismatchError,
    UserNotFoundError,
)
from .types import (
    Bucket,
    BucketPermissionLevel,
    ManagedRole,
    Permission,
    Policy,
    PolicySummary,
    SSOConfig,
    TabulatorTable,
    UnmanagedRole,
    User,
    UserLastLoginContext,
)
