# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import APIKeySelection


class AdminApiKeysList(BaseModel):
    admin: "AdminApiKeysListAdmin"


class AdminApiKeysListAdmin(BaseModel):
    api_keys: "AdminApiKeysListAdminApiKeys" = Field(alias="apiKeys")


class AdminApiKeysListAdminApiKeys(BaseModel):
    list: List["AdminApiKeysListAdminApiKeysList"]


class AdminApiKeysListAdminApiKeysList(APIKeySelection):
    pass


AdminApiKeysList.model_rebuild()
AdminApiKeysListAdmin.model_rebuild()
AdminApiKeysListAdminApiKeys.model_rebuild()
