# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import APIKeySelection


class AdminApiKeyGet(BaseModel):
    admin: "AdminApiKeyGetAdmin"


class AdminApiKeyGetAdmin(BaseModel):
    api_keys: "AdminApiKeyGetAdminApiKeys" = Field(alias="apiKeys")


class AdminApiKeyGetAdminApiKeys(BaseModel):
    get: Optional["AdminApiKeyGetAdminApiKeysGet"]


class AdminApiKeyGetAdminApiKeysGet(APIKeySelection):
    pass


AdminApiKeyGet.model_rebuild()
AdminApiKeyGetAdmin.model_rebuild()
AdminApiKeyGetAdminApiKeys.model_rebuild()
