# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import APIKeySelection


class ApiKeysList(BaseModel):
    me: Optional["ApiKeysListMe"]


class ApiKeysListMe(BaseModel):
    api_keys: List["ApiKeysListMeApiKeys"] = Field(alias="apiKeys")


class ApiKeysListMeApiKeys(APIKeySelection):
    pass


ApiKeysList.model_rebuild()
ApiKeysListMe.model_rebuild()
