# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import InvalidInputSelection


class ApiKeyRevoke(BaseModel):
    api_key_revoke: Union["ApiKeyRevokeApiKeyRevokeOk", "ApiKeyRevokeApiKeyRevokeInvalidInput"] = Field(
        alias="apiKeyRevoke", discriminator="typename__"
    )


class ApiKeyRevokeApiKeyRevokeOk(BaseModel):
    typename__: Literal["Ok"] = Field(alias="__typename")


class ApiKeyRevokeApiKeyRevokeInvalidInput(InvalidInputSelection):
    typename__: Literal["InvalidInput"] = Field(alias="__typename")


ApiKeyRevoke.model_rebuild()
