# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import ManagedRoleSelection, UnmanagedRoleSelection


class DefaultRoleGet(BaseModel):
    default_role: Optional[
        Annotated[
            Union[
                "DefaultRoleGetDefaultRoleUnmanagedRole",
                "DefaultRoleGetDefaultRoleManagedRole",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="defaultRole")


class DefaultRoleGetDefaultRoleUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class DefaultRoleGetDefaultRoleManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


DefaultRoleGet.model_rebuild()
