# Generated by ariadne-codegen
# Source: ../../../shared/graphql/schema.graphql

from enum import Enum


class SearchResultOrder(str, Enum):
    BEST_MATCH = "BEST_MATCH"
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"
    LEX_ASC = "LEX_ASC"
    LEX_DESC = "LEX_DESC"
