# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import APIKeyStatus, BucketPermissionLevel


class APIKeySelection(BaseModel):
    id: str
    name: str
    fingerprint: str
    created_at: datetime = Field(alias="createdAt")
    expires_at: datetime = Field(alias="expiresAt")
    last_used_at: datetime | None = Field(alias="lastUsedAt")
    status: APIKeyStatus
    user_email: str = Field(alias="userEmail")


class BucketConfigSelection(BaseModel):
    name: str
    title: str
    icon_url: str | None = Field(alias="iconUrl")
    description: str | None
    overview_url: str | None = Field(alias="overviewUrl")
    tags: list[str] | None
    relevance_score: int = Field(alias="relevanceScore")
    last_indexed: datetime | None = Field(alias="lastIndexed")
    sns_notification_arn: str | None = Field(alias="snsNotificationArn")
    scanner_parallel_shards_depth: int | None = Field(alias="scannerParallelShardsDepth")
    skip_meta_data_indexing: bool | None = Field(alias="skipMetaDataIndexing")
    file_extensions_to_index: list[str] | None = Field(alias="fileExtensionsToIndex")
    index_content_bytes: int | None = Field(alias="indexContentBytes")
    prefixes: list[str]


class InvalidInputSelection(BaseModel):
    errors: list["InvalidInputSelectionErrors"]


class InvalidInputSelectionErrors(BaseModel):
    path: str | None
    message: str
    name: str
    context: Any | None


class PermissionSelection(BaseModel):
    bucket: "PermissionSelectionBucket"
    level: BucketPermissionLevel


class PermissionSelectionBucket(BaseModel):
    name: str


class PolicySummarySelection(BaseModel):
    id: str
    title: str
    arn: str
    managed: bool
    permissions: list["PolicySummarySelectionPermissions"]


class PolicySummarySelectionPermissions(PermissionSelection):
    pass


class RoleBucketPermissionSelection(BaseModel):
    bucket: "RoleBucketPermissionSelectionBucket"
    level: BucketPermissionLevel


class RoleBucketPermissionSelectionBucket(BaseModel):
    name: str


class ManagedRoleSelection(BaseModel):
    typename__: str = Field(alias="__typename")
    id: str
    name: str
    arn: str
    policies: list["ManagedRoleSelectionPolicies"]
    permissions: list["ManagedRoleSelectionPermissions"]


class ManagedRoleSelectionPolicies(PolicySummarySelection):
    pass


class ManagedRoleSelectionPermissions(RoleBucketPermissionSelection):
    pass


class OperationErrorSelection(BaseModel):
    message: str
    name: str
    context: Any | None


class PolicySelection(BaseModel):
    id: str
    title: str
    arn: str
    managed: bool
    permissions: list["PolicySelectionPermissions"]
    roles: list["PolicySelectionRoles"]


class PolicySelectionPermissions(PermissionSelection):
    pass


class PolicySelectionRoles(ManagedRoleSelection):
    pass


class UnmanagedRoleSelection(BaseModel):
    typename__: str = Field(alias="__typename")
    id: str
    name: str
    arn: str


class UserSelection(BaseModel):
    name: str
    email: str
    date_joined: datetime = Field(alias="dateJoined")
    last_login: datetime = Field(alias="lastLogin")
    is_active: bool = Field(alias="isActive")
    is_admin: bool = Field(alias="isAdmin")
    is_sso_only: bool = Field(alias="isSsoOnly")
    is_service: bool = Field(alias="isService")
    role: (
        Annotated[
            Union["UserSelectionRoleUnmanagedRole", "UserSelectionRoleManagedRole"], Field(discriminator="typename__")
        ]
        | None
    )
    extra_roles: list[
        Annotated[
            Union[
                "UserSelectionExtraRolesUnmanagedRole",
                "UserSelectionExtraRolesManagedRole",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="extraRoles")


class UserSelectionRoleUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class UserSelectionRoleManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


class UserSelectionExtraRolesUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class UserSelectionExtraRolesManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


class SsoConfigSelection(BaseModel):
    text: str
    timestamp: datetime
    uploader: "SsoConfigSelectionUploader"


class SsoConfigSelectionUploader(UserSelection):
    pass


APIKeySelection.model_rebuild()
BucketConfigSelection.model_rebuild()
InvalidInputSelection.model_rebuild()
PermissionSelection.model_rebuild()
PolicySummarySelection.model_rebuild()
RoleBucketPermissionSelection.model_rebuild()
ManagedRoleSelection.model_rebuild()
OperationErrorSelection.model_rebuild()
PolicySelection.model_rebuild()
UnmanagedRoleSelection.model_rebuild()
UserSelection.model_rebuild()
SsoConfigSelection.model_rebuild()
