# Generated by ariadne-codegen
# Source: ../../../shared/graphql/schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BucketPermissionLevel


class APIKeyCreateInput(BaseModel):
    name: str
    expires_in_days: int = Field(alias="expiresInDays", default=90)


class BucketAddInput(BaseModel):
    name: str
    title: str
    icon_url: str | None = Field(alias="iconUrl", default=None)
    description: str | None = None
    linked_data: Any | None = Field(alias="linkedData", default=None)
    overview_url: str | None = Field(alias="overviewUrl", default=None)
    tags: list[str] | None = None
    relevance_score: int | None = Field(alias="relevanceScore", default=None)
    sns_notification_arn: str | None = Field(alias="snsNotificationArn", default=None)
    scanner_parallel_shards_depth: int | None = Field(alias="scannerParallelShardsDepth", default=None)
    skip_meta_data_indexing: bool | None = Field(alias="skipMetaDataIndexing", default=None)
    file_extensions_to_index: list[str] | None = Field(alias="fileExtensionsToIndex", default=None)
    index_content_bytes: int | None = Field(alias="indexContentBytes", default=None)
    delay_scan: bool | None = Field(alias="delayScan", default=None)
    browsable: bool | None = None
    prefixes: list[str] | None = None


class BucketUpdateInput(BaseModel):
    title: str
    icon_url: str | None = Field(alias="iconUrl", default=None)
    description: str | None = None
    linked_data: Any | None = Field(alias="linkedData", default=None)
    overview_url: str | None = Field(alias="overviewUrl", default=None)
    tags: list[str] | None = None
    relevance_score: int | None = Field(alias="relevanceScore", default=None)
    sns_notification_arn: str | None = Field(alias="snsNotificationArn", default=None)
    scanner_parallel_shards_depth: int | None = Field(alias="scannerParallelShardsDepth", default=None)
    skip_meta_data_indexing: bool | None = Field(alias="skipMetaDataIndexing", default=None)
    file_extensions_to_index: list[str] | None = Field(alias="fileExtensionsToIndex", default=None)
    index_content_bytes: int | None = Field(alias="indexContentBytes", default=None)
    browsable: bool | None = None
    prefixes: list[str] | None = None


class PermissionInput(BaseModel):
    bucket: str
    level: BucketPermissionLevel


class UnmanagedRoleInput(BaseModel):
    name: str
    arn: str


class ManagedRoleInput(BaseModel):
    name: str
    policies: list[str]


class ManagedPolicyInput(BaseModel):
    title: str
    permissions: list["PermissionInput"]
    roles: list[str]


class UnmanagedPolicyInput(BaseModel):
    title: str
    arn: str
    roles: list[str]


class UserInput(BaseModel):
    name: str
    email: str
    role: str
    extra_roles: list[str] | None = Field(alias="extraRoles", default=None)


ManagedPolicyInput.model_rebuild()
