# Generated by ariadne-codegen
# Source: ../../../shared/graphql/schema.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class UserInput(BaseModel):
    name: str
    email: str
    role: str
    extra_roles: Optional[List[str]] = Field(alias="extraRoles", default=None)
