# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import PolicySelection


class PoliciesList(BaseModel):
    policies: List["PoliciesListPolicies"]


class PoliciesListPolicies(PolicySelection):
    pass


PoliciesList.model_rebuild()
