# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import PolicySelection


class PolicyGet(BaseModel):
    policy: Optional["PolicyGetPolicy"]


class PolicyGetPolicy(PolicySelection):
    pass


PolicyGet.model_rebuild()
