# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import InvalidInputSelection, OperationErrorSelection


class PolicyDelete(BaseModel):
    policy_delete: Union[
        "PolicyDeletePolicyDeleteOk",
        "PolicyDeletePolicyDeleteInvalidInput",
        "PolicyDeletePolicyDeleteOperationError",
    ] = Field(alias="policyDelete", discriminator="typename__")


class PolicyDeletePolicyDeleteOk(BaseModel):
    typename__: Literal["Ok"] = Field(alias="__typename")


class PolicyDeletePolicyDeleteInvalidInput(InvalidInputSelection):
    typename__: Literal["InvalidInput"] = Field(alias="__typename")


class PolicyDeletePolicyDeleteOperationError(OperationErrorSelection):
    typename__: Literal["OperationError"] = Field(alias="__typename")


PolicyDelete.model_rebuild()
