# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import InvalidInputSelection, OperationErrorSelection, PolicySelection


class PolicyUpdateManaged(BaseModel):
    policy_update_managed: Union[
        "PolicyUpdateManagedPolicyUpdateManagedPolicy",
        "PolicyUpdateManagedPolicyUpdateManagedInvalidInput",
        "PolicyUpdateManagedPolicyUpdateManagedOperationError",
    ] = Field(alias="policyUpdateManaged", discriminator="typename__")


class PolicyUpdateManagedPolicyUpdateManagedPolicy(PolicySelection):
    typename__: Literal["Policy"] = Field(alias="__typename")


class PolicyUpdateManagedPolicyUpdateManagedInvalidInput(InvalidInputSelection):
    typename__: Literal["InvalidInput"] = Field(alias="__typename")


class PolicyUpdateManagedPolicyUpdateManagedOperationError(OperationErrorSelection):
    typename__: Literal["OperationError"] = Field(alias="__typename")


PolicyUpdateManaged.model_rebuild()
