# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import ManagedRoleSelection, UnmanagedRoleSelection


class RoleGet(BaseModel):
    role: Optional[
        Annotated[
            Union["RoleGetRoleUnmanagedRole", "RoleGetRoleManagedRole"],
            Field(discriminator="typename__"),
        ]
    ]


class RoleGetRoleUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class RoleGetRoleManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


RoleGet.model_rebuild()
