# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel


class RoleDelete(BaseModel):
    role_delete: Union[
        "RoleDeleteRoleDeleteRoleDeleteSuccess",
        "RoleDeleteRoleDeleteRoleDoesNotExist",
        "RoleDeleteRoleDeleteRoleNameReserved",
        "RoleDeleteRoleDeleteRoleNameUsedBySsoConfig",
        "RoleDeleteRoleDeleteRoleAssigned",
    ] = Field(alias="roleDelete", discriminator="typename__")


class RoleDeleteRoleDeleteRoleDeleteSuccess(BaseModel):
    typename__: Literal["RoleDeleteSuccess"] = Field(alias="__typename")


class RoleDeleteRoleDeleteRoleDoesNotExist(BaseModel):
    typename__: Literal["RoleDoesNotExist"] = Field(alias="__typename")


class RoleDeleteRoleDeleteRoleNameReserved(BaseModel):
    typename__: Literal["RoleNameReserved"] = Field(alias="__typename")


class RoleDeleteRoleDeleteRoleNameUsedBySsoConfig(BaseModel):
    typename__: Literal["RoleNameUsedBySsoConfig"] = Field(alias="__typename")


class RoleDeleteRoleDeleteRoleAssigned(BaseModel):
    typename__: Literal["RoleAssigned"] = Field(alias="__typename")


RoleDelete.model_rebuild()
