# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import ManagedRoleSelection, UnmanagedRoleSelection


class RoleUpdateManaged(BaseModel):
    role_update_managed: Union[
        "RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccess",
        "RoleUpdateManagedRoleUpdateManagedRoleNameReserved",
        "RoleUpdateManagedRoleUpdateManagedRoleNameExists",
        "RoleUpdateManagedRoleUpdateManagedRoleNameInvalid",
        "RoleUpdateManagedRoleUpdateManagedRoleNameUsedBySsoConfig",
        "RoleUpdateManagedRoleUpdateManagedRoleIsManaged",
        "RoleUpdateManagedRoleUpdateManagedRoleIsUnmanaged",
        "RoleUpdateManagedRoleUpdateManagedRoleHasTooManyPoliciesToAttach",
    ] = Field(alias="roleUpdateManaged", discriminator="typename__")


class RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccess(BaseModel):
    typename__: Literal["RoleUpdateSuccess"] = Field(alias="__typename")
    role: Union[
        "RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccessRoleUnmanagedRole",
        "RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccessRoleManagedRole",
    ] = Field(discriminator="typename__")


class RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccessRoleUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccessRoleManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleNameReserved(BaseModel):
    typename__: Literal["RoleNameReserved"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleNameExists(BaseModel):
    typename__: Literal["RoleNameExists"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleNameInvalid(BaseModel):
    typename__: Literal["RoleNameInvalid"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleNameUsedBySsoConfig(BaseModel):
    typename__: Literal["RoleNameUsedBySsoConfig"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleIsManaged(BaseModel):
    typename__: Literal["RoleIsManaged"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleIsUnmanaged(BaseModel):
    typename__: Literal["RoleIsUnmanaged"] = Field(alias="__typename")


class RoleUpdateManagedRoleUpdateManagedRoleHasTooManyPoliciesToAttach(BaseModel):
    typename__: Literal["RoleHasTooManyPoliciesToAttach"] = Field(alias="__typename")


RoleUpdateManaged.model_rebuild()
RoleUpdateManagedRoleUpdateManagedRoleUpdateSuccess.model_rebuild()
