# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import ManagedRoleSelection, UnmanagedRoleSelection


class GetRoles(BaseModel):
    roles: List[
        Annotated[
            Union["GetRolesRolesUnmanagedRole", "GetRolesRolesManagedRole"],
            Field(discriminator="typename__"),
        ]
    ]


class GetRolesRolesUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class GetRolesRolesManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


GetRoles.model_rebuild()
