# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetSsoConfig(BaseModel):
    admin: "GetSsoConfigAdmin"


class GetSsoConfigAdmin(BaseModel):
    sso_config: Optional[str] = Field(alias="ssoConfig")


GetSsoConfig.model_rebuild()
