# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import InvalidInputSelection, OperationErrorSelection


class SetSsoConfig(BaseModel):
    admin: "SetSsoConfigAdmin"


class SetSsoConfigAdmin(BaseModel):
    set_sso_config: Union[
        "SetSsoConfigAdminSetSsoConfigOk",
        "SetSsoConfigAdminSetSsoConfigInvalidInput",
        "SetSsoConfigAdminSetSsoConfigOperationError",
    ] = Field(alias="setSsoConfig", discriminator="typename__")


class SetSsoConfigAdminSetSsoConfigOk(BaseModel):
    typename__: Literal["Ok"] = Field(alias="__typename")
    underscore_named_field_: Optional[bool] = Field(alias="_")


class SetSsoConfigAdminSetSsoConfigInvalidInput(InvalidInputSelection):
    typename__: Literal["InvalidInput"] = Field(alias="__typename")


class SetSsoConfigAdminSetSsoConfigOperationError(OperationErrorSelection):
    typename__: Literal["OperationError"] = Field(alias="__typename")


SetSsoConfig.model_rebuild()
SetSsoConfigAdmin.model_rebuild()
