# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserSelection


class SsoConfigGet(BaseModel):
    admin: "SsoConfigGetAdmin"


class SsoConfigGetAdmin(BaseModel):
    sso_config: Optional["SsoConfigGetAdminSsoConfig"] = Field(alias="ssoConfig")


class SsoConfigGetAdminSsoConfig(BaseModel):
    text: str
    timestamp: datetime
    uploader: "SsoConfigGetAdminSsoConfigUploader"


class SsoConfigGetAdminSsoConfigUploader(UserSelection):
    pass


SsoConfigGet.model_rebuild()
SsoConfigGetAdmin.model_rebuild()
SsoConfigGetAdminSsoConfig.model_rebuild()
