coverage:
  status:
    project:
      default:
        target: 80%
        paths:
          - '!**/tests/'
          - '!**/test/'
        informational: true
    patch:
      default:
        target: 80%
      diff:
        target: 80%
      informational: true

flag_management:
  default_rules:
    statuses:
      - name_prefix: 'auto-'
        type: project
        threshold: 0.1
        target: 80%
      - name_prefix: 'auto-'
        type: patch
        target: 80%
  individual_flags:
    # Looks like these are left from testing codecov flags,
    # but it's not clear why they are still appear, ignore them.
    - name: 'msys'
      statuses: []
    - name: 'linux-gnu'
      statuses: []
