# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class InvalidInputSelection(BaseModel):
    errors: List["InvalidInputSelectionErrors"]


class InvalidInputSelectionErrors(BaseModel):
    path: Optional[str]
    message: str
    name: str
    context: Optional[Any]


class ManagedRoleSelection(BaseModel):
    id: str
    name: str
    arn: str


class OperationErrorSelection(BaseModel):
    message: str
    name: str
    context: Optional[Any]


class UnmanagedRoleSelection(BaseModel):
    id: str
    name: str
    arn: str


InvalidInputSelection.model_rebuild()
ManagedRoleSelection.model_rebuild()
OperationErrorSelection.model_rebuild()
UnmanagedRoleSelection.model_rebuild()
