# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import UserSelection


class GetUsers(BaseModel):
    admin: "GetUsersAdmin"


class GetUsersAdmin(BaseModel):
    user: "GetUsersAdminUser"


class GetUsersAdminUser(BaseModel):
    list: List["GetUsersAdminUserList"]


class GetUsersAdminUserList(UserSelection):
    pass


GetUsers.model_rebuild()
GetUsersAdmin.model_rebuild()
GetUsersAdminUser.model_rebuild()
