# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import ManagedRoleSelection, UnmanagedRoleSelection


class GetRole(BaseModel):
    role: Optional[
        Annotated[
            Union["GetRoleRoleUnmanagedRole", "GetRoleRoleManagedRole"],
            Field(discriminator="typename__"),
        ]
    ]


class GetRoleRoleUnmanagedRole(UnmanagedRoleSelection):
    typename__: Literal["UnmanagedRole"] = Field(alias="__typename")


class GetRoleRoleManagedRole(ManagedRoleSelection):
    typename__: Literal["ManagedRole"] = Field(alias="__typename")


GetRole.model_rebuild()
