// flow-typed signature: 10422d8d67ff1d69b4a2fd80c1014c92
// flow-typed version: <<STUB>>/eslint-plugin-redux-saga_v^0.9.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-redux-saga/lib/rules/no-unhandled-errors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-redux-saga/lib/rules/no-yield-in-race' {
  declare module.exports: any;
}

declare module 'eslint-plugin-redux-saga/lib/rules/yield-effects' {
  declare module.exports: any;
}

declare module 'eslint-plugin-redux-saga/lib/utils/effects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-redux-saga/index' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga'>;
}
declare module 'eslint-plugin-redux-saga/index.js' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga'>;
}
declare module 'eslint-plugin-redux-saga/lib/rules/no-unhandled-errors.js' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga/lib/rules/no-unhandled-errors'>;
}
declare module 'eslint-plugin-redux-saga/lib/rules/no-yield-in-race.js' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga/lib/rules/no-yield-in-race'>;
}
declare module 'eslint-plugin-redux-saga/lib/rules/yield-effects.js' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga/lib/rules/yield-effects'>;
}
declare module 'eslint-plugin-redux-saga/lib/utils/effects.js' {
  declare module.exports: $Exports<'eslint-plugin-redux-saga/lib/utils/effects'>;
}
