// flow-typed signature: 46169d4311c8c7e3bdae56d5a6c9a68a
// flow-typed version: <<STUB>>/fetch-mock_v^6.4.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-mock/dist/es5/client-bundle' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/fetch-handler' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/index' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/inspecting' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/response-builder' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/set-up-and-tear-down' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/status-text' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/server' {
  declare module.exports: any;
}

declare module 'fetch-mock/scripts/support-fetch-mock' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/fetch-handler' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/index' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/inspecting' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/response-builder' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/set-up-and-tear-down' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/lib/status-text' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-mock/dist/es5/client-bundle.js' {
  declare module.exports: $Exports<'fetch-mock/dist/es5/client-bundle'>;
}
declare module 'fetch-mock/es5/client.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client'>;
}
declare module 'fetch-mock/es5/lib/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/compile-route'>;
}
declare module 'fetch-mock/es5/lib/fetch-handler.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/fetch-handler'>;
}
declare module 'fetch-mock/es5/lib/index.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/index'>;
}
declare module 'fetch-mock/es5/lib/inspecting.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/inspecting'>;
}
declare module 'fetch-mock/es5/lib/response-builder.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/response-builder'>;
}
declare module 'fetch-mock/es5/lib/set-up-and-tear-down.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/set-up-and-tear-down'>;
}
declare module 'fetch-mock/es5/lib/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/status-text'>;
}
declare module 'fetch-mock/es5/server.js' {
  declare module.exports: $Exports<'fetch-mock/es5/server'>;
}
declare module 'fetch-mock/scripts/support-fetch-mock.js' {
  declare module.exports: $Exports<'fetch-mock/scripts/support-fetch-mock'>;
}
declare module 'fetch-mock/src/client.js' {
  declare module.exports: $Exports<'fetch-mock/src/client'>;
}
declare module 'fetch-mock/src/lib/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/compile-route'>;
}
declare module 'fetch-mock/src/lib/fetch-handler.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/fetch-handler'>;
}
declare module 'fetch-mock/src/lib/index.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/index'>;
}
declare module 'fetch-mock/src/lib/inspecting.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/inspecting'>;
}
declare module 'fetch-mock/src/lib/response-builder.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/response-builder'>;
}
declare module 'fetch-mock/src/lib/set-up-and-tear-down.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/set-up-and-tear-down'>;
}
declare module 'fetch-mock/src/lib/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/src/lib/status-text'>;
}
declare module 'fetch-mock/src/server.js' {
  declare module.exports: $Exports<'fetch-mock/src/server'>;
}
