// flow-typed signature: 2113c3b865523b8fe0cfe98a10e81636
// flow-typed version: <<STUB>>/ngrok_v^2.2.25/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ngrok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ngrok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ngrok/postinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ngrok/index' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/index.js' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/postinstall.js' {
  declare module.exports: $Exports<'ngrok/postinstall'>;
}
