// flow-typed signature: 863609e6eed7ed360f7b09edb2dcf824
// flow-typed version: <<STUB>>/plop_v^1.9.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plop/example/plopfile' {
  declare module.exports: any;
}

declare module 'plop/src/console-out' {
  declare module.exports: any;
}

declare module 'plop/src/plop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plop/example/plopfile.js' {
  declare module.exports: $Exports<'plop/example/plopfile'>;
}
declare module 'plop/src/console-out.js' {
  declare module.exports: $Exports<'plop/src/console-out'>;
}
declare module 'plop/src/plop.js' {
  declare module.exports: $Exports<'plop/src/plop'>;
}
