// flow-typed signature: 62427473bdf7e13a393329443a2170fc
// flow-typed version: <<STUB>>/raven-for-redux_v^1.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven-for-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven-for-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raven-for-redux/built/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raven-for-redux/built/index.js' {
  declare module.exports: $Exports<'raven-for-redux/built/index'>;
}
