// flow-typed signature: 1061a108d3a4860be39c36d3582bed3f
// flow-typed version: <<STUB>>/react-stripe-checkout_v^2.6.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stripe-checkout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stripe-checkout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stripe-checkout/dist/main' {
  declare module.exports: any;
}

declare module 'react-stripe-checkout/spec' {
  declare module.exports: any;
}

declare module 'react-stripe-checkout/StripeCheckout' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stripe-checkout/dist/main.js' {
  declare module.exports: $Exports<'react-stripe-checkout/dist/main'>;
}
declare module 'react-stripe-checkout/spec.js' {
  declare module.exports: $Exports<'react-stripe-checkout/spec'>;
}
declare module 'react-stripe-checkout/StripeCheckout.js' {
  declare module.exports: $Exports<'react-stripe-checkout/StripeCheckout'>;
}
