// flow-typed signature: f436a34bbb0d9fb1d81af2b58f6858f7
// flow-typed version: <<STUB>>/sanitize.css_v^4.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
