// flow-typed signature: 47b79691862360cb1f1d58f571205694
// flow-typed version: <<STUB>>/sanitize.css_v^4.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
