[project]
name = "es-ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sergey Fedoseev", email = "fedoseev.sergey@quiltdata.io" }
]
requires-python = ">=3.11"
dependencies = [
    "pytest-cov~=6.2",
    "quilt-shared[boto,es]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
quilt-shared = { url = "https://github.com/quiltdata/quilt/archive/bc9c170fc936f3110c8ba9249984efb2b8893f2e.zip", subdirectory = "py-shared" }

[dependency-groups]
test = [
    "pytest~=8.4",
]
