name: Deploy S3 Proxy to ECR

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-s3-proxy.yaml
      - 's3-proxy/**'

jobs:
  deploy-s3-proxy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: quiltdata/gh-actions/docker-build-publish@docker-build-publish
        with:
          dockerfile_path: s3-proxy/Dockerfile
          docker_context_path: s3-proxy
          image_name: quiltdata/s3-proxy
          mp_image_name: quilt-data/quilt-payg-s3-proxy
          push_targets: '["prod","govcloud","mp"]'
          role_name: Quilt
