name: Test GraphQL code generation

on:
  push:
    paths:
      - '.github/workflows/test-graphql-codegen.yaml'
      - 'shared/graphql/schema.graphql'
      - 'api/python/quilt3-admin/**'
      - 'api/python/quilt3/admin/_graphql_client/**'
      - 'api/python/quilt3-graphql/**'
      - 'api/python/quilt3/_graphql_client/**'
  pull_request:
    paths:
      - '.github/workflows/test-graphql-codegen.yaml'
      - 'shared/graphql/schema.graphql'
      - 'api/python/quilt3-admin/**'
      - 'api/python/quilt3/admin/_graphql_client/**'
      - 'api/python/quilt3-graphql/**'
      - 'api/python/quilt3/_graphql_client/**'
  merge_group:

jobs:
  test-graphql-codegen:
    name: test GraphQL generated code is up-to-date
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/python/quilt3-graphql
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'api/python/quilt3-graphql/requirements.txt'
      - run: pip install -r requirements.txt
      - run: rm -r ../quilt3/_graphql_client
      - run: ariadne-codegen
      - name: Check for changes
        run: git diff --exit-code
